language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh github_package hadley/testthat"
- "./travis-tool.sh install_r testthatsomemore R6"
- "./travis-tool.sh github_package jimhester/covr@e3e137fdf27b6e0dfba2f8d8f25b616b1fb81db9"
- "./travis-tool.sh github_package robertzk/objectdiff"
script: "./travis-tool.sh run_tests"
after_failure:
  - ./travis-tool.sh dump_logs
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: mrJnMQv+nNC2lbEBlsS9q3Uaqevt0bRSMp8Nw7OBLQwVP+gfqkz6omvlatYhMwumiZxUZZdb1qPggx0gx8N0C3galJoaq9U1fjtZnX0nAL519uYbwNGlK6Z0Pq/27BW3014ZVrRcTKQa0xJM5/LfN1tzD+hyAyJiocOEIkdABAA=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
env:
- global:
  - WARNINGS_ARE_ERRORS=1
  - _R_CHECK_FORCE_SUGGESTS_=0
