language: r
sudo: required
warnings_are_errors: true

r_github_packages:
  - kirillseva/covr
  - hadley/devtools
  - smbache/magrittr
  - hadley/testthat
  - kirillseva/objectdiff@stagerunner_debug_message
  - robertzk/testthatsomemore

after_success:
  - "Rscript -e 'library(covr);coveralls()'"

notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: mrJnMQv+nNC2lbEBlsS9q3Uaqevt0bRSMp8Nw7OBLQwVP+gfqkz6omvlatYhMwumiZxUZZdb1qPggx0gx8N0C3galJoaq9U1fjtZnX0nAL519uYbwNGlK6Z0Pq/27BW3014ZVrRcTKQa0xJM5/LfN1tzD+hyAyJiocOEIkdABAA=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
